import { initializeApp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import { getDatabase, ref, get, set, update, push, onValue, runTransaction, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";

const $=s=>document.querySelector(s), appEl=$("#app");
const configured=!Object.values(firebaseConfig).some(v=>String(v).includes("PASTE_"));
let fb,auth,db,user=null,role=null,room=null,teamId=null,teamName="",soundId=1,roomData=null,unsub=null,countTimer=null;
const SOUNDS=[
  [1,"Classic Bell","🔔"],[2,"Game Show","🎙️"],[3,"School Bell","🏫"],[4,"Ding Dong","🛎️"],[5,"Gong","🥁"],[6,"Bright Bell","✨"],[7,"Buzzer","⚡"],
  [8,"Arcade Coin","🪙"],[9,"Laser","🚀"],[10,"Robot","🤖"],[11,"Retro Jump","🕹️"],[12,"Power Up","🎮"],[13,"Digital Ping","📡"],[14,"Glitch","💾"],
  [15,"Boing","🫧"],[16,"Pop","🎈"],[17,"Squeak","🐤"],[18,"Whistle","📣"],[19,"Magic","🪄"],[20,"Bubble","🫧"],[21,"Spring","🌀"],
  [22,"Epic Hit","💥"],[23,"Drum Hit","🥁"],[24,"Bass Drop","🔊"],[25,"Trumpet","🎺"],[26,"Victory Ping","🏆"],[27,"Space Zap","🛸"],[28,"Crystal","💎"],
  [29,"QuizZap","⚡"],[30,"PakKom Pulse","PQ"]
];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const newCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const net=s=>$("#net").textContent=s;
function toast(s){let x=$("#toast");x.textContent=s;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
const audioCache=new Map();
let audioCtx=null;
function synthSound(id){
 try{
  audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();
  const ctx=audioCtx, now=ctx.currentTime, master=ctx.createGain(); master.connect(ctx.destination); master.gain.setValueAtTime(.18,now);
  const profiles={8:[880,1320,.12,"square"],9:[1400,320,.22,"sawtooth"],10:[180,520,.28,"square"],11:[330,660,.18,"square"],12:[440,880,.3,"triangle"],13:[1200,900,.16,"sine"],14:[180,1500,.18,"sawtooth"],15:[180,520,.32,"sine"],16:[700,250,.08,"sine"],17:[1500,1100,.12,"square"],18:[900,1200,.3,"sine"],19:[660,1320,.38,"sine"],20:[420,780,.18,"sine"],21:[240,720,.32,"triangle"],22:[120,55,.3,"sawtooth"],23:[160,70,.18,"triangle"],24:[90,42,.45,"sine"],25:[520,780,.4,"sawtooth"],26:[660,990,.42,"triangle"],27:[1200,180,.3,"sawtooth"],28:[1100,1760,.38,"sine"],29:[880,220,.2,"square"],30:[392,784,.45,"triangle"]};
  const [f1,f2,d,type]=profiles[id]||profiles[29], o=ctx.createOscillator(), g=ctx.createGain(); o.type=type;o.connect(g);g.connect(master);o.frequency.setValueAtTime(f1,now);o.frequency.exponentialRampToValueAtTime(Math.max(30,f2),now+d);g.gain.setValueAtTime(.9,now);g.gain.exponentialRampToValueAtTime(.001,now+d);o.start(now);o.stop(now+d+.02);
 }catch{}
}
function beep(id=1){try{let n=Math.max(1,Math.min(30,+id||1));if(n>7)return synthSound(n);let a=audioCache.get(n);if(!a){a=new Audio(`sounds/Sound ${n}.mp3`);a.preload="auto";audioCache.set(n,a)}a.currentTime=0;a.play()?.catch(()=>{})}catch{}}
function speak(name){try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(name+" menekan bel");u.lang="id-ID";u.rate=.9;speechSynthesis.speak(u)}catch{}}
function teams(){return Object.entries(roomData?.teams||{}).map(([id,t])=>({id,...t})).sort((a,b)=>(b.score||0)-(a.score||0)||String(a.name).localeCompare(String(b.name)))}
function rounds(){return Object.entries(roomData?.rounds||{}).map(([id,r])=>({id,...r})).sort((a,b)=>a.number-b.number)}
function winner(){return teams().find(t=>t.id===roomData?.buzzer?.winnerTeamId)}
function myTeam(){return teams().find(t=>t.id===teamId)}
function storeSession(){if(room&&teamId)localStorage.setItem("pq_team",JSON.stringify({room,teamId}));}
function clearSession(){localStorage.removeItem("pq_team")}

async function init(){
 if(!configured){net("● PERLU FIREBASE");home();toast("Isi firebase-config.js terlebih dahulu.");return}
 try{fb=initializeApp(firebaseConfig);auth=getAuth(fb);db=getDatabase(fb);net("● AUTENTIKASI...");await signInAnonymously(auth);onAuthStateChanged(auth,u=>{user=u;if(u){net("● FIREBASE SIAP");route()}})}catch(e){console.error(e);net("● ERROR");home();toast("Firebase belum tersambung: "+e.message)}
}
function watchRoom(){if(unsub)unsub();let oldWinner=null;unsub=onValue(ref(db,`rooms/${room}`),snap=>{let prev=oldWinner;roomData=snap.val();if(!roomData){toast("Room sudah tidak tersedia.");return home()}oldWinner=roomData.buzzer?.winnerTeamId||null;if(oldWinner&&oldWinner!==prev){let t=roomData.teams?.[oldWinner];if(t){beep(t.soundId);speak(t.name)}}render()})}
function route(){let p=new URLSearchParams(location.search),display=p.get("display"),join=p.get("room");if(display){role="display";room=display.toUpperCase();watchRoom();return}if(join){room=join.toUpperCase();role="player";checkRoom(true);return}let s=JSON.parse(localStorage.getItem("pq_team")||"null");if(s?.room&&s?.teamId){room=s.room;teamId=s.teamId;role="player";get(ref(db,`rooms/${room}/teams/${teamId}`)).then(x=>x.exists()?watchRoom():(clearSession(),home()));return}home()}
function home(){if(unsub){unsub();unsub=null}role=null;room=null;teamId=null;roomData=null;appEl.innerHTML=`<div class="wrap"><section class="card hero"><div class="mark">PQ</div><h1>PAKKOM-QUIZBUZZ</h1><p>Digital classroom buzzer real-time untuk permainan kompetitif di kelas.</p><div class="buttons"><button id="make">Buat Permainan</button><button id="join" class="secondary">Gabung Permainan</button></div></section><section class="card"><div class="grid"><div><b>⚡ Atomic Buzzer</b><p class="muted small">Pemenang pertama ditentukan transaction Firebase.</p></div><div><b>⏱️ Countdown</b><p class="muted small">3–2–1 sebelum bel aktif.</p></div><div><b>📺 Layar Arena</b><p class="muted small">Tampilan khusus proyektor.</p></div><div><b>↩️ Undo & Rebuzz</b><p class="muted small">Kontrol pertandingan lebih aman.</p></div></div></section></div>`;$("#make").onclick=makePage;$("#join").onclick=joinPage}
function makePage(){if(!user)return toast("Menunggu Firebase...");appEl.innerHTML=`<div class="wrap"><section class="card"><h2>Buat Permainan</h2><div class="grid"><label>Maksimal tim<input id="max" type="number" min="2" max="50" value="5"></label><label>Nilai benar<input id="yes" type="number" value="10"></label><label>Nilai salah<input id="no" type="number" value="5"></label><label>Nama babak<input id="rn" value="Babak 1" maxlength="30"></label></div><div class="buttons"><button id="go">Buat Room</button><button id="back" class="secondary">Kembali</button></div></section></div>`;$("#go").onclick=createRoom;$("#back").onclick=home}
async function createRoom(){net("● MEMBUAT ROOM...");let max=Math.max(2,Math.min(50,+$("#max").value||5)),yes=+$("#yes").value||10,no=+$("#no").value||5,name=$("#rn").value.trim()||"Babak 1";for(let i=0;i<20;i++){let c=newCode(),r=ref(db,`rooms/${c}`),s=await get(r);if(s.exists())continue;let data={hostUid:user.uid,createdAt:Date.now(),maxTeams:max,locked:false,round:{number:1,name,correct:yes,wrong:no},rounds:{r1:{number:1,name,correct:yes,wrong:no}},buzzer:{open:false,winnerTeamId:null,countdown:0,question:0,blocked:{}},teams:{},history:{}};await set(r,data);room=c;role="host";net("● REAL-TIME");watchRoom();return}toast("Gagal membuat kode room.")}
function joinPage(){appEl.innerHTML=`<div class="wrap"><section class="card"><h2>Gabung Permainan</h2><p class="muted">Masukkan kode 6 karakter dari host.</p><input id="code" maxlength="6" placeholder="ABC123" style="text-transform:uppercase"><div class="buttons"><button id="go">Lanjut</button><button id="back" class="secondary">Kembali</button></div></section></div>`;$("#go").onclick=()=>{room=$("#code").value.trim().toUpperCase();checkRoom(false)};$("#back").onclick=home}
async function checkRoom(fromLink=false){if(!/^[A-Z0-9]{6}$/.test(room||"")){if(fromLink)return home();return toast("Kode harus 6 karakter.")}let s=await get(ref(db,`rooms/${room}`));if(!s.exists())return toast("Room tidak ditemukan.");roomData=s.val();if(roomData.locked)return toast("Room sedang dikunci host.");role="player";teamPage()}
function teamPage(){appEl.innerHTML=`<div class="wrap"><section class="card"><span class="pill">ROOM ${room}</span><h2>Nama & Suara Tim</h2><input id="name" maxlength="25" placeholder="Contoh: GARUDA" autocomplete="off"><div class="soundtools"><span class="muted small">30 suara · suara yang sama boleh dipakai tim lain</span><button id="randomSound" class="secondary">🎲 Acak</button></div><div id="sounds" class="soundgrid"></div><div class="buttons"><button id="preview" class="secondary">▶ Preview</button><button id="go">Masuk Permainan</button></div></section></div>`;let sg=$("#sounds");const draw=()=>{sg.innerHTML=SOUNDS.map(([id,name,ico])=>`<button class="sound ${id===soundId?"active":""}" data-id="${id}"><span class="soundico">${ico}</span><span><b>${name}</b><small>▶ dengar</small></span></button>`).join("");sg.querySelectorAll(".sound").forEach(b=>b.onclick=()=>{soundId=+b.dataset.id;draw();beep(soundId)})};draw();$("#randomSound").onclick=()=>{soundId=SOUNDS[Math.floor(Math.random()*SOUNDS.length)][0];draw();beep(soundId)};$("#preview").onclick=()=>beep(soundId);$("#go").onclick=joinTeam}
async function joinTeam(){teamName=$("#name").value.trim();if(!teamName)return toast("Nama tim wajib diisi.");let snap=await get(ref(db,`rooms/${room}`));roomData=snap.val();if(roomData.locked)return toast("Room sudah dikunci.");let ts=teams();if(ts.length>=roomData.maxTeams)return toast("Room sudah penuh.");if(ts.some(t=>t.name.toLowerCase()===teamName.toLowerCase()))return toast("Nama tim sudah dipakai.");teamId=push(ref(db,`rooms/${room}/teams`)).key;await set(ref(db,`rooms/${room}/teams/${teamId}`),{ownerUid:user.uid,name:teamName,score:0,soundId,joinedAt:serverTimestamp()});storeSession();watchRoom()}
function board(big=false){let ts=teams();if(!ts.length)return `<div class="empty">Belum ada tim.</div>`;return ts.map((t,i)=>`<div class="team ${t.id===roomData.buzzer?.winnerTeamId?"winner":""} ${big?"arena-team":""}"><div class="row"><div><span class="rank">${i+1}</span><b>${esc(t.name)}</b></div><span class="score">${t.score||0}</span></div></div>`).join("")}
async function countdown(){if(roomData.buzzer?.open||roomData.buzzer?.countdown)return;await update(ref(db,`rooms/${room}/buzzer`),{open:false,winnerTeamId:null,countdown:3,blocked:{},question:(roomData.buzzer?.question||0)+1});let n=3;clearInterval(countTimer);countTimer=setInterval(async()=>{n--;if(n>0)await update(ref(db,`rooms/${room}/buzzer`),{countdown:n});else{clearInterval(countTimer);await update(ref(db,`rooms/${room}/buzzer`),{countdown:0,open:true,winnerTeamId:null,openedAt:serverTimestamp()})}},1000)}
async function buzz(){let me=myTeam();if(!me||roomData.buzzer?.blocked?.[teamId])return;let b=ref(db,`rooms/${room}/buzzer`);let result=await runTransaction(b,current=>{if(!current||current.open!==true||current.winnerTeamId)return;return {...current,open:false,winnerTeamId:teamId,winnerUid:user.uid,wonAt:Date.now()}});if(!result.committed)toast("Bel sudah diambil tim lain.")}
async function judge(ok,rebuzz=false){let w=winner();if(!w)return;let pts=ok?roomData.round.correct:-roomData.round.wrong;let histKey=push(ref(db,`rooms/${room}/history`)).key;let before=w.score||0,after=before+pts;let patch={};patch[`teams/${w.id}/score`]=after;patch[`history/${histKey}`]={type:"judge",teamId:w.id,teamName:w.name,ok,points:pts,before,after,round:roomData.round.number,question:roomData.buzzer.question,at:Date.now()};patch[`lastAction`]={historyKey:histKey,teamId:w.id,before,after,at:Date.now()};patch[`buzzer/winnerTeamId`]=null;patch[`buzzer/open`]=rebuzz;patch[`buzzer/countdown`]=0;if(rebuzz&&!ok)patch[`buzzer/blocked/${w.id}`]=true;else patch[`buzzer/blocked`]={};await update(ref(db,`rooms/${room}`),patch)}
async function cancelBuzz(){let w=winner();if(!w)return toast("Belum ada buzz yang bisa dibatalkan.");let hk=push(ref(db,`rooms/${room}/history`)).key;let patch={};patch[`history/${hk}`]={type:"cancel_buzz",teamId:w.id,teamName:w.name,round:roomData.round.number,question:roomData.buzzer.question,at:Date.now()};patch[`buzzer/winnerTeamId`]=null;patch[`buzzer/winnerUid`]=null;patch[`buzzer/wonAt`]=null;patch[`buzzer/open`]=true;await update(ref(db,`rooms/${room}`),patch);toast("Buzz dibatalkan. Bel dibuka kembali tanpa perubahan skor.")}
async function cancelQuestion(){let q=roomData.buzzer?.question||0;if(!q)return toast("Belum ada soal aktif.");let hk=push(ref(db,`rooms/${room}/history`)).key;let patch={};patch[`history/${hk}`]={type:"cancel_question",round:roomData.round.number,question:q,at:Date.now()};patch[`buzzer/open`]=false;patch[`buzzer/winnerTeamId`]=null;patch[`buzzer/winnerUid`]=null;patch[`buzzer/wonAt`]=null;patch[`buzzer/countdown`]=0;patch[`buzzer/blocked`]={};patch[`buzzer/cancelledQuestion`]=q;await update(ref(db,`rooms/${room}`),patch);toast(`Soal ${q} dibatalkan. Tidak ada skor yang berubah.`)}
async function undo(){let a=roomData.lastAction;if(!a)return toast("Belum ada skor yang bisa di-undo.");let h=roomData.history?.[a.historyKey];if(!h)return toast("Riwayat undo tidak ditemukan.");let patch={};patch[`teams/${a.teamId}/score`]=a.before;patch[`history/${a.historyKey}/undone`]=true;patch[`lastAction`]=null;await update(ref(db,`rooms/${room}`),patch);toast("Skor terakhir dibatalkan.")}
async function toggleLock(){await update(ref(db,`rooms/${room}`),{locked:!roomData.locked})}
async function kick(id){if(!confirm("Keluarkan tim ini dari room?"))return;await set(ref(db,`rooms/${room}/teams/${id}`),null)}
function nextRoundForm(){appEl.insertAdjacentHTML("beforeend",`<div class="modal" id="roundModal"><section class="card"><h2>Babak Berikutnya</h2><div class="grid"><label>Nama<input id="newrn" value="Babak ${roomData.round.number+1}"></label><label>Benar<input id="newyes" type="number" value="${roomData.round.correct}"></label><label>Salah<input id="newno" type="number" value="${roomData.round.wrong}"></label></div><div class="buttons"><button id="start">Mulai Babak</button><button id="cancel" class="secondary">Batal</button></div></section></div>`);$("#cancel").onclick=()=>$("#roundModal").remove();$("#start").onclick=startRound}
async function startRound(){let n=roomData.round.number+1,name=$("#newrn").value.trim()||`Babak ${n}`,correct=+$("#newyes").value||0,wrong=+$("#newno").value||0;let patch={round:{number:n,name,correct,wrong},buzzer:{open:false,winnerTeamId:null,countdown:0,question:0,blocked:{}}};patch[`rounds/r${n}`]={number:n,name,correct,wrong};await update(ref(db,`rooms/${room}`),patch);$("#roundModal").remove()}
function qrUrl(){return `${location.origin}${location.pathname}?room=${room}`}
function hostRender(){let w=winner(),b=roomData.buzzer||{};appEl.innerHTML=`<div class="wrap"><section class="card"><div class="row"><div><span class="pill">HOST</span><h2>${esc(roomData.round.name)}</h2><p class="muted">Babak ${roomData.round.number} · Benar +${roomData.round.correct} · Salah -${roomData.round.wrong}</p></div><span class="pill">${teams().length}/${roomData.maxTeams} TIM</span></div><div class="code">${room}</div><div id="qr" class="qr"></div><div class="buttons"><button id="display" class="secondary">📺 LAYAR PROYEKTOR</button><button id="lock" class="secondary">${roomData.locked?"🔓 BUKA ROOM":"🔒 KUNCI ROOM"}</button></div></section><section class="card"><div class="row"><h2>Papan Skor</h2><button id="undo" class="secondary" ${roomData.lastAction?"":"disabled"}>↩ UNDO SKOR</button></div>${board()}<div class="manage">${teams().map(t=>`<button class="secondary kick" data-id="${t.id}">Keluarkan ${esc(t.name)}</button>`).join("")}</div></section><section class="card controller">${b.countdown?`<div class="count">${b.countdown}</div><p class="center muted">Bersiap...</p>`:w?`<div class="notice win"><div class="gold">BEL PERTAMA</div><h1>${esc(w.name)}</h1><div class="buttons"><button class="good" id="correct">✓ BENAR +${roomData.round.correct}</button><button class="bad" id="wrongrebuzz">✕ SALAH & REBUZZ -${roomData.round.wrong}</button><button class="bad" id="wrong">✕ SALAH & SELESAI</button></div><div class="buttons safety"><button class="secondary" id="cancelbuzz">↻ BATALKAN BUZZ</button><button class="cancelq" id="cancelquestion">⊘ BATALKAN SOAL</button></div></div>`:b.open?`<div class="notice"><h2>🔔 BEL TERBUKA</h2><p>Menunggu peserta tercepat...</p><div class="buttons safety"><button class="cancelq" id="cancelquestion">⊘ BATALKAN SOAL</button></div></div>`:`<button id="startbuzz" class="startbuzz">MULAI 3 · 2 · 1</button>`}<div class="buttons"><button id="round" class="warn">➜ BABAK BERIKUTNYA</button></div></section><section class="card"><h3>Riwayat Babak</h3>${rounds().map(r=>`<div class="history"><b>Babak ${r.number} · ${esc(r.name)}</b><div class="small muted">Benar +${r.correct} · Salah -${r.wrong}</div></div>`).join("")}</section></div>`;
 loadQR();$("#display").onclick=()=>window.open(`${location.pathname}?display=${room}`,"_blank");$("#lock").onclick=toggleLock;$("#undo").onclick=undo;document.querySelectorAll(".kick").forEach(x=>x.onclick=()=>kick(x.dataset.id));if($("#startbuzz"))$("#startbuzz").onclick=countdown;if($("#correct"))$("#correct").onclick=()=>judge(true,false);if($("#wrongrebuzz"))$("#wrongrebuzz").onclick=()=>judge(false,true);if($("#wrong"))$("#wrong").onclick=()=>judge(false,false);if($("#cancelbuzz"))$("#cancelbuzz").onclick=cancelBuzz;if($("#cancelquestion"))$("#cancelquestion").onclick=cancelQuestion;$("#round").onclick=nextRoundForm}
async function loadQR(){let box=$("#qr");if(!box)return;box.innerHTML=`<img alt="QR Join" src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(qrUrl())}"><div class="small muted">Scan untuk masuk langsung ke room</div>`}
function playerRender(){let me=myTeam(),w=winner(),b=roomData.buzzer||{};if(!me){clearSession();return teamPage()}appEl.innerHTML=`<div class="wrap"><section class="card"><div class="row"><div><span class="pill">${esc(roomData.round.name)}</span><h2>${esc(me.name)}</h2></div><div class="score">${me.score||0} poin</div></div></section><section class="card center">${b.countdown?`<div class="count">${b.countdown}</div><p class="muted">Jangan tekan sebelum BEL terbuka.</p>`:w?`<div class="notice ${w.id===teamId?"win":""}"><div>${w.id===teamId?"🎉 KAMU MENANGI BEL":"BEL SUDAH DIAMBIL"}</div><h1>${esc(w.name)}</h1></div>`:b.blocked?.[teamId]?`<div class="notice">Jawaban timmu salah. Tim lain sedang berebut.</div>`:b.open?`<p class="muted">Sekarang!</p><button class="buzz" id="buzz">BEL</button>`:`<div class="notice">⏳ Menunggu host...</div>`}</section><section class="card"><h2>Papan Skor</h2>${board()}</section><button id="leave" class="secondary leave">Keluar dari tim</button></div>`;if($("#buzz"))$("#buzz").onclick=buzz;$("#leave").onclick=()=>{clearSession();teamId=null;teamPage()}}
function displayRender(){let w=winner(),b=roomData.buzzer||{};appEl.innerHTML=`<div class="arena"><div class="arena-top"><div><span class="pill">PAKKOM-QUIZBUZZ</span><h1>${esc(roomData.round.name)}</h1></div><div class="arena-code">ROOM ${room}</div></div><div class="arena-main">${b.countdown?`<div class="mega-count">${b.countdown}</div>`:w?`<div class="arena-winner"><div>BEL PERTAMA</div><h1>${esc(w.name)}</h1></div>`:b.open?`<div class="arena-open">🔔 BUZZ!</div>`:`<div class="arena-wait">SIAPKAN TIM</div>`}</div><div class="arena-board">${board(true)}</div></div>`}
function render(){if(!roomData)return;if(role==="host")hostRender();else if(role==="display")displayRender();else if(role==="player"&&teamId)playerRender()}
init();
